// <auto-generated />
using System;
using Infrastructrure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructrure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250504191647_first_setup")]
    partial class first_setup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.Property<int>("idParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idParticipant"));

                    b.Property<bool>("activityStatus")
                        .HasColumnType("bit");

                    b.Property<int>("connectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("connectionStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("idSession")
                        .HasColumnType("int");

                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idParticipant");

                    b.HasIndex("idSession");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Property<int>("idSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSession"));

                    b.Property<Guid?>("acces_code")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("active_status")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("interation_count")
                        .HasColumnType("int");

                    b.Property<int>("max_participants")
                        .HasColumnType("int");

                    b.Property<int>("presentation_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("idSession");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.HasOne("Domain.Entities.Session", "session")
                        .WithMany("Participants")
                        .HasForeignKey("idSession")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("session");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
