// <auto-generated />
using System;
using Infrastructrure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructrure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AccesCode", b =>
                {
                    b.Property<int>("idCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCode"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("idCode");

                    b.ToTable("AccesCode");
                });

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.Property<int>("idParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idParticipant"));

                    b.Property<bool>("activityStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("connectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("connectionStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("idSession")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idParticipant");

                    b.HasIndex("idSession");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("access_code")
                        .HasColumnType("int");

                    b.Property<bool>("active_status")
                        .HasColumnType("bit");

                    b.Property<Guid>("created_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("currentSlide")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("interation_count")
                        .HasColumnType("int");

                    b.Property<int>("max_participants")
                        .HasColumnType("int");

                    b.Property<int>("presentation_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId");

                    b.HasIndex("access_code")
                        .IsUnique()
                        .HasFilter("[access_code] IS NOT NULL");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Domain.Entities.Participant", b =>
                {
                    b.HasOne("Domain.Entities.Session", "session")
                        .WithMany("Participants")
                        .HasForeignKey("idSession")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("session");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.HasOne("Domain.Entities.AccesCode", "AccesCode")
                        .WithOne("Session")
                        .HasForeignKey("Domain.Entities.Session", "access_code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AccesCode");
                });

            modelBuilder.Entity("Domain.Entities.AccesCode", b =>
                {
                    b.Navigation("Session")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
